{% set name = "c-blosc2" %}
{% set version = "2.0.0.beta4" %}

package:
  name: c-blosc2
  version: {{ version }}

source:
  url: https://github.com/Blosc/c-blosc2/archive/v{{ version }}.tar.gz
  sha256: ef6a88bf87c45c506c42febc1ae3204ad7dbaf42f1fb32990d2c90f0c781cf0b

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('c-blosc2') }}

requirements:
  build:
    - cmake
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:

test:
  commands:
    - test -e $PREFIX/include/blosc2.h                    # [unix]
    - test -e $PREFIX/include/blosc2-export.h             # [unix]
    - test -e $PREFIX/lib/libblosc2.a                     # [unix]
    - test -e $PREFIX/lib/libblosc2${SHLIB_EXT}           # [unix]
    - if not exist %LIBRARY_INC%\\blosc2.h exit 1         # [win]
    - if not exist %LIBRARY_INC%\\blosc-export2.h exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\blosc2.dll exit 1       # [win]
    - if not exist %LIBRARY_LIB%\\blosc2.lib exit 1       # [win]
    - if not exist %LIBRARY_LIB%\\libblosc2.lib exit 1    # [win]

about:
  home: https://github.com/Blosc/c-blosc2
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'A blocking, shuffling C compression library, with persistency'
    
  description: |
    Next generation of C-Blosc library bringing in a new container (schunk) that can optionally be persisted (frame).  Also, more filters, codecs and other bells and whistles like pre-filter support have been added.  The API tries to be as compatible as possible with the original C-Blosc.

extra:
  recipe-maintainers:
    - FrancescAlted
